### ISSUE TITLE
User Time Line

### ISSUE THREAD

**Issue by sbsreyes** [sbsreyes/study-up#4]
realizar la maquetacion del time line de los usuarios con tag/home

**Comment by Juansereyes7** [comment]
El time line del usuario está diseñado en el modulo, bajo la descodificación de Home, llamando como funcion el layout en donde se encuentra diseñado el header para su carga automática

**Comment by sbsreyes** [comment]
Se da cierre al issue, ya que el time line fue diseñado, el comentario anterior demuestra como fue agregado al proyecto y a los modulos específicos de la carpeta raíz
